package cn.edu.wtu.wtr.media.object;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Date;
import lombok.Data;

/**
 * @TableName contents
 */
@Data
public class Contents implements Serializable {
    /**
     * 
     *
     * @mbg.generated Tue Feb 02 19:52:04 CST 2021
     */
    private Integer id;

    /**
     * 账号
     *
     * @mbg.generated Tue Feb 02 19:52:04 CST 2021
     */
    private String account;

    /**
     * 类别
     *
     * @mbg.generated Tue Feb 02 19:52:04 CST 2021
     */
    private String type;

    /**
     * 风格
     *
     * @mbg.generated Tue Feb 02 19:52:04 CST 2021
     */
    private String style;

    /**
     * 内容
     *
     * @mbg.generated Tue Feb 02 19:52:04 CST 2021
     */
    private String value;

    /**
     * 分布时间
     *
     * @mbg.generated Tue Feb 02 19:52:04 CST 2021
     */
    private LocalDateTime createTime = LocalDateTime.now();

    /**
     * 超链接
     *
     * @mbg.generated Tue Feb 02 19:52:04 CST 2021
     */
    private String ulr;

    /**
     * 平台
     *
     * @mbg.generated Tue Feb 02 19:52:04 CST 2021
     */
    private String platform;

    /**
     * 阅读/浏览
     *
     * @mbg.generated Tue Feb 02 19:52:04 CST 2021
     */
    private Integer viewPage;

    /**
     * 转发/在看
     *
     * @mbg.generated Tue Feb 02 19:52:04 CST 2021
     */
    private Integer transmit;

    /**
     * 评论
     *
     * @mbg.generated Tue Feb 02 19:52:04 CST 2021
     */
    private Integer comment;

    /**
     * 点赞
     *
     * @mbg.generated Tue Feb 02 19:52:04 CST 2021
     */
    private Integer like;

    /**
     * 投币
     *
     * @mbg.generated Tue Feb 02 19:52:04 CST 2021
     */
    private Integer coin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contents
     *
     * @mbg.generated Tue Feb 02 19:52:04 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Contents other = (Contents) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAccount() == null ? other.getAccount() == null : this.getAccount().equals(other.getAccount()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getStyle() == null ? other.getStyle() == null : this.getStyle().equals(other.getStyle()))
            && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUlr() == null ? other.getUlr() == null : this.getUlr().equals(other.getUlr()))
            && (this.getPlatform() == null ? other.getPlatform() == null : this.getPlatform().equals(other.getPlatform()))
            && (this.getViewPage() == null ? other.getViewPage() == null : this.getViewPage().equals(other.getViewPage()))
            && (this.getTransmit() == null ? other.getTransmit() == null : this.getTransmit().equals(other.getTransmit()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
            && (this.getLike() == null ? other.getLike() == null : this.getLike().equals(other.getLike()))
            && (this.getCoin() == null ? other.getCoin() == null : this.getCoin().equals(other.getCoin()));
    }

    /**
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAccount() == null) ? 0 : getAccount().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getStyle() == null) ? 0 : getStyle().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUlr() == null) ? 0 : getUlr().hashCode());
        result = prime * result + ((getPlatform() == null) ? 0 : getPlatform().hashCode());
        result = prime * result + ((getViewPage() == null) ? 0 : getViewPage().hashCode());
        result = prime * result + ((getTransmit() == null) ? 0 : getTransmit().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + ((getLike() == null) ? 0 : getLike().hashCode());
        result = prime * result + ((getCoin() == null) ? 0 : getCoin().hashCode());
        return result;
    }

    /**
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", account=").append(account);
        sb.append(", type=").append(type);
        sb.append(", style=").append(style);
        sb.append(", value=").append(value);
        sb.append(", createTime=").append(createTime);
        sb.append(", ulr=").append(ulr);
        sb.append(", platform=").append(platform);
        sb.append(", viewPage=").append(viewPage);
        sb.append(", transmit=").append(transmit);
        sb.append(", comment=").append(comment);
        sb.append(", like=").append(like);
        sb.append(", coin=").append(coin);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}