package cn.edu.wtu.wtr.media.object;

import lombok.Data;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * null
 *
 * @TableName courseInfo
 */
@Data
public class Courseinfo implements Serializable {
    /**
     * @mbg.generated 2021-03-16 12:48:20
     */
    private Integer cid;

    /**
     * @mbg.generated 2021-03-16 12:48:20
     */
    private Integer id;

    /**
     * @mbg.generated 2021-03-16 12:48:20
     */
    private String sid;

    /**
     * 姓名
     *
     * @mbg.generated 2021-03-16 12:48:20
     */
    private String name;

    /**
     * @mbg.generated 2021-03-16 12:48:20
     */
    private String year;

    /**
     * @mbg.generated 2021-03-16 12:48:20
     */
    private String term;

    /**
     * 课程信息
     *
     * @mbg.generated 2021-03-16 12:48:20
     */
    private String courses;

    /**
     * @mbg.generated 2021-03-16 12:48:20
     */
    private LocalDateTime dateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table courseInfo
     *
     * @mbg.generated 2021-03-16 12:48:20
     */
    private static final long serialVersionUID = 1L;


    public Courseinfo() {
    }

    public Courseinfo(Integer id, String sid, String name, String year, String term, String courses, LocalDateTime dateTime) {
        this();
        this.id = id;
        this.sid = sid;
        this.name = name;
        this.year = year;
        this.term = term;
        this.courses = courses;
        this.dateTime = dateTime;
    }

    /**
     * @mbg.generated 2021-03-16 12:48:20
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Courseinfo other = (Courseinfo) that;
        return (this.getCid() == null ? other.getCid() == null : this.getCid().equals(other.getCid()))
                && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getSid() == null ? other.getSid() == null : this.getSid().equals(other.getSid()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getYear() == null ? other.getYear() == null : this.getYear().equals(other.getYear()))
                && (this.getTerm() == null ? other.getTerm() == null : this.getTerm().equals(other.getTerm()))
                && (this.getCourses() == null ? other.getCourses() == null : this.getCourses().equals(other.getCourses()))
                && (this.getDateTime() == null ? other.getDateTime() == null : this.getDateTime().equals(other.getDateTime()));
    }

    /**
     * @mbg.generated 2021-03-16 12:48:20
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCid() == null) ? 0 : getCid().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSid() == null) ? 0 : getSid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getYear() == null) ? 0 : getYear().hashCode());
        result = prime * result + ((getTerm() == null) ? 0 : getTerm().hashCode());
        result = prime * result + ((getCourses() == null) ? 0 : getCourses().hashCode());
        result = prime * result + ((getDateTime() == null) ? 0 : getDateTime().hashCode());
        return result;
    }

    /**
     * @mbg.generated 2021-03-16 12:48:20
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cid=").append(cid);
        sb.append(", id=").append(id);
        sb.append(", sid=").append(sid);
        sb.append(", name=").append(name);
        sb.append(", year=").append(year);
        sb.append(", term=").append(term);
        sb.append(", courses=").append(courses);
        sb.append(", dateTime=").append(dateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}