package cn.edu.wtu.wtr.media.object;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 * null
 * @TableName courseInfo
 */
@Data
public class Courseinfo implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-15 22:25:35
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated 2021-03-15 22:25:35
     */
    private String sid;

    /**
     * 姓名
     *
     * @mbg.generated 2021-03-15 22:25:35
     */
    private String name;

    /**
     * 课程信息
     *
     * @mbg.generated 2021-03-15 22:25:35
     */
    private String courses;

    /**
     * 
     *
     * @mbg.generated 2021-03-15 22:25:35
     */
    private LocalDateTime dateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table courseInfo
     *
     * @mbg.generated 2021-03-15 22:25:35
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * @mbg.generated 2021-03-15 22:25:35
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Courseinfo other = (Courseinfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSid() == null ? other.getSid() == null : this.getSid().equals(other.getSid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCourses() == null ? other.getCourses() == null : this.getCourses().equals(other.getCourses()))
            && (this.getDateTime() == null ? other.getDateTime() == null : this.getDateTime().equals(other.getDateTime()));
    }

    /**
     *
     * @mbg.generated 2021-03-15 22:25:35
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSid() == null) ? 0 : getSid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCourses() == null) ? 0 : getCourses().hashCode());
        result = prime * result + ((getDateTime() == null) ? 0 : getDateTime().hashCode());
        return result;
    }

    /**
     *
     * @mbg.generated 2021-03-15 22:25:35
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sid=").append(sid);
        sb.append(", name=").append(name);
        sb.append(", courses=").append(courses);
        sb.append(", dateTime=").append(dateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}