package cn.edu.wtu.wtr.media.object;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 * 动态
 * @TableName dynamic
 */
@Data
public class Dynamic implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    private Integer id;

    /**
     * 默认ID
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    private String did;

    /**
     * 账号
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    private String account;

    /**
     * 
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    private String platform;

    /**
     * 类型
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    private String type;

    /**
     * 风格
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    private String style;

    /**
     * 内容
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    private String value;

    /**
     * 时间
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    private LocalDateTime createTime;

    /**
     * 连接
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    private String url;

    /**
     * 阅读
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    private Integer view;

    /**
     * 评论
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    private Integer comment;

    /**
     * 
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    private Integer transmit;

    /**
     * 
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    private Integer like;

    /**
     * 
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    private Integer coin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dynamic
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Dynamic other = (Dynamic) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDid() == null ? other.getDid() == null : this.getDid().equals(other.getDid()))
            && (this.getAccount() == null ? other.getAccount() == null : this.getAccount().equals(other.getAccount()))
            && (this.getPlatform() == null ? other.getPlatform() == null : this.getPlatform().equals(other.getPlatform()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getStyle() == null ? other.getStyle() == null : this.getStyle().equals(other.getStyle()))
            && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getView() == null ? other.getView() == null : this.getView().equals(other.getView()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
            && (this.getTransmit() == null ? other.getTransmit() == null : this.getTransmit().equals(other.getTransmit()))
            && (this.getLike() == null ? other.getLike() == null : this.getLike().equals(other.getLike()))
            && (this.getCoin() == null ? other.getCoin() == null : this.getCoin().equals(other.getCoin()));
    }

    /**
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDid() == null) ? 0 : getDid().hashCode());
        result = prime * result + ((getAccount() == null) ? 0 : getAccount().hashCode());
        result = prime * result + ((getPlatform() == null) ? 0 : getPlatform().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getStyle() == null) ? 0 : getStyle().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getView() == null) ? 0 : getView().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + ((getTransmit() == null) ? 0 : getTransmit().hashCode());
        result = prime * result + ((getLike() == null) ? 0 : getLike().hashCode());
        result = prime * result + ((getCoin() == null) ? 0 : getCoin().hashCode());
        return result;
    }

    /**
     *
     * @mbg.generated 2021-02-27 21:30:07
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", did=").append(did);
        sb.append(", account=").append(account);
        sb.append(", platform=").append(platform);
        sb.append(", type=").append(type);
        sb.append(", style=").append(style);
        sb.append(", value=").append(value);
        sb.append(", createTime=").append(createTime);
        sb.append(", url=").append(url);
        sb.append(", view=").append(view);
        sb.append(", comment=").append(comment);
        sb.append(", transmit=").append(transmit);
        sb.append(", like=").append(like);
        sb.append(", coin=").append(coin);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}