package cn.edu.wtu.wtr.media.object;

import java.io.Serializable;
import lombok.Data;

/**
 * 系统配置
 * @TableName wtr
 */
@Data
public class Wtr implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-16 15:46:41
     */
    private Integer id;

    /**
     * 键
     *
     * @mbg.generated 2021-03-16 15:46:41
     */
    private String key;

    /**
     * 内容
     *
     * @mbg.generated 2021-03-16 15:46:41
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wtr
     *
     * @mbg.generated 2021-03-16 15:46:41
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * @mbg.generated 2021-03-16 15:46:41
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Wtr other = (Wtr) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getKey() == null ? other.getKey() == null : this.getKey().equals(other.getKey()))
            && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()));
    }

    /**
     *
     * @mbg.generated 2021-03-16 15:46:41
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getKey() == null) ? 0 : getKey().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        return result;
    }

    /**
     *
     * @mbg.generated 2021-03-16 15:46:41
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", key=").append(key);
        sb.append(", value=").append(value);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}