server:
  port: 9230

db-host: 127.0.0.1
db-port: 3306
db-base: WTR
db-username: root
db-password: root

spring:
  datasource:
    username: ${db-username}
    password: ${db-password}
    url: jdbc:mysql://${db-host}:${db-port}/${db-base}?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  # druid 连接池
    druid:
      max-active: 30 # 最大连接数
      min-idle: 5    # 最小连接量
      max-wait: 10000 # 最大等待时间 10s
      validation-query: SELECT 'wtr' # 8小时空闲查询一次避免连接关闭
      time-between-eviction-runs-millis: 60000 # 空闲连接检查间隔
      min-evictable-idle-time-millis: 300000  # 空闲阈值

#Mybaits
mybatis:
  mapper-locations: classpath:dao/*Dao.xml

logging:
  level:
    cn.edu.wtu.wtr.media.dao.**: debug